/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as authVerifyOtpRouteImport } from './routes/(auth)/verify-otp'
import { Route as authNewPasswordRouteImport } from './routes/(auth)/new-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as OnboardingLawyerRouteRouteImport } from './routes/onboarding/lawyer/route'
import { Route as OnboardingClientRouteRouteImport } from './routes/onboarding/client/route'
import { Route as OnboardingLawyerIndexRouteImport } from './routes/onboarding/lawyer/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as OnboardingLawyerStep1RouteImport } from './routes/onboarding/lawyer/step-1'
import { Route as OnboardingLawyerSpecializationsRouteImport } from './routes/onboarding/lawyer/specializations'
import { Route as OnboardingLawyerProfileRouteImport } from './routes/onboarding/lawyer/profile'
import { Route as OnboardingLawyerCredentialsRouteImport } from './routes/onboarding/lawyer/credentials'
import { Route as OnboardingLawyerBasicsRouteImport } from './routes/onboarding/lawyer/basics'
import { Route as OnboardingClientSpecializationRouteImport } from './routes/onboarding/client/specialization'
import { Route as OnboardingClientLocationRouteImport } from './routes/onboarding/client/location'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const authVerifyOtpRoute = authVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authNewPasswordRoute = authNewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const OnboardingLawyerRouteRoute = OnboardingLawyerRouteRouteImport.update({
  id: '/onboarding/lawyer',
  path: '/onboarding/lawyer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientRouteRoute = OnboardingClientRouteRouteImport.update({
  id: '/onboarding/client',
  path: '/onboarding/client',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLawyerIndexRoute = OnboardingLawyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingLawyerRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const OnboardingLawyerStep1Route = OnboardingLawyerStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => OnboardingLawyerRouteRoute,
} as any)
const OnboardingLawyerSpecializationsRoute =
  OnboardingLawyerSpecializationsRouteImport.update({
    id: '/specializations',
    path: '/specializations',
    getParentRoute: () => OnboardingLawyerRouteRoute,
  } as any)
const OnboardingLawyerProfileRoute = OnboardingLawyerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingLawyerRouteRoute,
} as any)
const OnboardingLawyerCredentialsRoute =
  OnboardingLawyerCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => OnboardingLawyerRouteRoute,
  } as any)
const OnboardingLawyerBasicsRoute = OnboardingLawyerBasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => OnboardingLawyerRouteRoute,
} as any)
const OnboardingClientSpecializationRoute =
  OnboardingClientSpecializationRouteImport.update({
    id: '/specialization',
    path: '/specialization',
    getParentRoute: () => OnboardingClientRouteRoute,
  } as any)
const OnboardingClientLocationRoute =
  OnboardingClientLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => OnboardingClientRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding/client': typeof OnboardingClientRouteRouteWithChildren
  '/onboarding/lawyer': typeof OnboardingLawyerRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/new-password': typeof authNewPasswordRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/dashboard': typeof protectedDashboardRoute
  '/onboarding/client/location': typeof OnboardingClientLocationRoute
  '/onboarding/client/specialization': typeof OnboardingClientSpecializationRoute
  '/onboarding/lawyer/basics': typeof OnboardingLawyerBasicsRoute
  '/onboarding/lawyer/credentials': typeof OnboardingLawyerCredentialsRoute
  '/onboarding/lawyer/profile': typeof OnboardingLawyerProfileRoute
  '/onboarding/lawyer/specializations': typeof OnboardingLawyerSpecializationsRoute
  '/onboarding/lawyer/step-1': typeof OnboardingLawyerStep1Route
  '/register': typeof authRegisterIndexRoute
  '/onboarding/lawyer/': typeof OnboardingLawyerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding/client': typeof OnboardingClientRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/new-password': typeof authNewPasswordRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/dashboard': typeof protectedDashboardRoute
  '/onboarding/client/location': typeof OnboardingClientLocationRoute
  '/onboarding/client/specialization': typeof OnboardingClientSpecializationRoute
  '/onboarding/lawyer/basics': typeof OnboardingLawyerBasicsRoute
  '/onboarding/lawyer/credentials': typeof OnboardingLawyerCredentialsRoute
  '/onboarding/lawyer/profile': typeof OnboardingLawyerProfileRoute
  '/onboarding/lawyer/specializations': typeof OnboardingLawyerSpecializationsRoute
  '/onboarding/lawyer/step-1': typeof OnboardingLawyerStep1Route
  '/register': typeof authRegisterIndexRoute
  '/onboarding/lawyer': typeof OnboardingLawyerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding/client': typeof OnboardingClientRouteRouteWithChildren
  '/onboarding/lawyer': typeof OnboardingLawyerRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/new-password': typeof authNewPasswordRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/onboarding/client/location': typeof OnboardingClientLocationRoute
  '/onboarding/client/specialization': typeof OnboardingClientSpecializationRoute
  '/onboarding/lawyer/basics': typeof OnboardingLawyerBasicsRoute
  '/onboarding/lawyer/credentials': typeof OnboardingLawyerCredentialsRoute
  '/onboarding/lawyer/profile': typeof OnboardingLawyerProfileRoute
  '/onboarding/lawyer/specializations': typeof OnboardingLawyerSpecializationsRoute
  '/onboarding/lawyer/step-1': typeof OnboardingLawyerStep1Route
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/onboarding/lawyer/': typeof OnboardingLawyerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding/client'
    | '/onboarding/lawyer'
    | '/forgot-password'
    | '/new-password'
    | '/verify-otp'
    | '/dashboard'
    | '/onboarding/client/location'
    | '/onboarding/client/specialization'
    | '/onboarding/lawyer/basics'
    | '/onboarding/lawyer/credentials'
    | '/onboarding/lawyer/profile'
    | '/onboarding/lawyer/specializations'
    | '/onboarding/lawyer/step-1'
    | '/register'
    | '/onboarding/lawyer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding/client'
    | '/forgot-password'
    | '/new-password'
    | '/verify-otp'
    | '/dashboard'
    | '/onboarding/client/location'
    | '/onboarding/client/specialization'
    | '/onboarding/lawyer/basics'
    | '/onboarding/lawyer/credentials'
    | '/onboarding/lawyer/profile'
    | '/onboarding/lawyer/specializations'
    | '/onboarding/lawyer/step-1'
    | '/register'
    | '/onboarding/lawyer'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/login'
    | '/onboarding/client'
    | '/onboarding/lawyer'
    | '/(auth)/forgot-password'
    | '/(auth)/new-password'
    | '/(auth)/verify-otp'
    | '/(protected)/dashboard'
    | '/onboarding/client/location'
    | '/onboarding/client/specialization'
    | '/onboarding/lawyer/basics'
    | '/onboarding/lawyer/credentials'
    | '/onboarding/lawyer/profile'
    | '/onboarding/lawyer/specializations'
    | '/onboarding/lawyer/step-1'
    | '/(auth)/register/'
    | '/onboarding/lawyer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingClientRouteRoute: typeof OnboardingClientRouteRouteWithChildren
  OnboardingLawyerRouteRoute: typeof OnboardingLawyerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/new-password': {
      id: '/(auth)/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof authNewPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/onboarding/lawyer': {
      id: '/onboarding/lawyer'
      path: '/onboarding/lawyer'
      fullPath: '/onboarding/lawyer'
      preLoaderRoute: typeof OnboardingLawyerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/client': {
      id: '/onboarding/client'
      path: '/onboarding/client'
      fullPath: '/onboarding/client'
      preLoaderRoute: typeof OnboardingClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/lawyer/': {
      id: '/onboarding/lawyer/'
      path: '/'
      fullPath: '/onboarding/lawyer/'
      preLoaderRoute: typeof OnboardingLawyerIndexRouteImport
      parentRoute: typeof OnboardingLawyerRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/onboarding/lawyer/step-1': {
      id: '/onboarding/lawyer/step-1'
      path: '/step-1'
      fullPath: '/onboarding/lawyer/step-1'
      preLoaderRoute: typeof OnboardingLawyerStep1RouteImport
      parentRoute: typeof OnboardingLawyerRouteRoute
    }
    '/onboarding/lawyer/specializations': {
      id: '/onboarding/lawyer/specializations'
      path: '/specializations'
      fullPath: '/onboarding/lawyer/specializations'
      preLoaderRoute: typeof OnboardingLawyerSpecializationsRouteImport
      parentRoute: typeof OnboardingLawyerRouteRoute
    }
    '/onboarding/lawyer/profile': {
      id: '/onboarding/lawyer/profile'
      path: '/profile'
      fullPath: '/onboarding/lawyer/profile'
      preLoaderRoute: typeof OnboardingLawyerProfileRouteImport
      parentRoute: typeof OnboardingLawyerRouteRoute
    }
    '/onboarding/lawyer/credentials': {
      id: '/onboarding/lawyer/credentials'
      path: '/credentials'
      fullPath: '/onboarding/lawyer/credentials'
      preLoaderRoute: typeof OnboardingLawyerCredentialsRouteImport
      parentRoute: typeof OnboardingLawyerRouteRoute
    }
    '/onboarding/lawyer/basics': {
      id: '/onboarding/lawyer/basics'
      path: '/basics'
      fullPath: '/onboarding/lawyer/basics'
      preLoaderRoute: typeof OnboardingLawyerBasicsRouteImport
      parentRoute: typeof OnboardingLawyerRouteRoute
    }
    '/onboarding/client/specialization': {
      id: '/onboarding/client/specialization'
      path: '/specialization'
      fullPath: '/onboarding/client/specialization'
      preLoaderRoute: typeof OnboardingClientSpecializationRouteImport
      parentRoute: typeof OnboardingClientRouteRoute
    }
    '/onboarding/client/location': {
      id: '/onboarding/client/location'
      path: '/location'
      fullPath: '/onboarding/client/location'
      preLoaderRoute: typeof OnboardingClientLocationRouteImport
      parentRoute: typeof OnboardingClientRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authNewPasswordRoute: typeof authNewPasswordRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authNewPasswordRoute: authNewPasswordRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedRouteRouteChildren {
  protectedDashboardRoute: typeof protectedDashboardRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardRoute: protectedDashboardRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface OnboardingClientRouteRouteChildren {
  OnboardingClientLocationRoute: typeof OnboardingClientLocationRoute
  OnboardingClientSpecializationRoute: typeof OnboardingClientSpecializationRoute
}

const OnboardingClientRouteRouteChildren: OnboardingClientRouteRouteChildren = {
  OnboardingClientLocationRoute: OnboardingClientLocationRoute,
  OnboardingClientSpecializationRoute: OnboardingClientSpecializationRoute,
}

const OnboardingClientRouteRouteWithChildren =
  OnboardingClientRouteRoute._addFileChildren(
    OnboardingClientRouteRouteChildren,
  )

interface OnboardingLawyerRouteRouteChildren {
  OnboardingLawyerBasicsRoute: typeof OnboardingLawyerBasicsRoute
  OnboardingLawyerCredentialsRoute: typeof OnboardingLawyerCredentialsRoute
  OnboardingLawyerProfileRoute: typeof OnboardingLawyerProfileRoute
  OnboardingLawyerSpecializationsRoute: typeof OnboardingLawyerSpecializationsRoute
  OnboardingLawyerStep1Route: typeof OnboardingLawyerStep1Route
  OnboardingLawyerIndexRoute: typeof OnboardingLawyerIndexRoute
}

const OnboardingLawyerRouteRouteChildren: OnboardingLawyerRouteRouteChildren = {
  OnboardingLawyerBasicsRoute: OnboardingLawyerBasicsRoute,
  OnboardingLawyerCredentialsRoute: OnboardingLawyerCredentialsRoute,
  OnboardingLawyerProfileRoute: OnboardingLawyerProfileRoute,
  OnboardingLawyerSpecializationsRoute: OnboardingLawyerSpecializationsRoute,
  OnboardingLawyerStep1Route: OnboardingLawyerStep1Route,
  OnboardingLawyerIndexRoute: OnboardingLawyerIndexRoute,
}

const OnboardingLawyerRouteRouteWithChildren =
  OnboardingLawyerRouteRoute._addFileChildren(
    OnboardingLawyerRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingClientRouteRoute: OnboardingClientRouteRouteWithChildren,
  OnboardingLawyerRouteRoute: OnboardingLawyerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
