/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionSuccessRouteImport } from './routes/subscription-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as publicSearchLawyerRouteImport } from './routes/(public)/search-lawyer'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as authVerifyOtpRouteImport } from './routes/(auth)/verify-otp'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authNewPasswordRouteImport } from './routes/(auth)/new-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as OnboardinglawyerRouteRouteImport } from './routes/onboarding/(lawyer)/route'
import { Route as OnboardingclientRouteRouteImport } from './routes/onboarding/(client)/route'
import { Route as protectedAdminRouteRouteImport } from './routes/(protected)/admin/route'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedAdminIndexRouteImport } from './routes/(protected)/admin/index'
import { Route as OnboardinglawyerStatusRouteImport } from './routes/onboarding/(lawyer)/status'
import { Route as OnboardinglawyerReviewRouteImport } from './routes/onboarding/(lawyer)/review'
import { Route as OnboardinglawyerLawyerSpecializationsRouteImport } from './routes/onboarding/(lawyer)/lawyer-specializations'
import { Route as OnboardinglawyerCredentialsRouteImport } from './routes/onboarding/(lawyer)/credentials'
import { Route as OnboardinglawyerBasicsRouteImport } from './routes/onboarding/(lawyer)/basics'
import { Route as OnboardingclientClientSpecializationsRouteImport } from './routes/onboarding/(client)/client-specializations'
import { Route as OnboardingclientClientLocationRouteImport } from './routes/onboarding/(client)/client-location'
import { Route as publicLawyerLawyerIdRouteImport } from './routes/(public)/lawyer.$lawyerId'
import { Route as protectedDashboardSearchLawyerRouteImport } from './routes/(protected)/dashboard/search-lawyer'
import { Route as protectedDashboardPlansRouteImport } from './routes/(protected)/dashboard/plans'
import { Route as protectedAdminUsersRouteImport } from './routes/(protected)/admin/users'
import { Route as protectedAdminStatisticsRouteImport } from './routes/(protected)/admin/statistics'
import { Route as protectedAdminLawyersRouteImport } from './routes/(protected)/admin/lawyers'
import { Route as protectedAdminClientsRouteImport } from './routes/(protected)/admin/clients'
import { Route as protectedAdminApplicationsRouteImport } from './routes/(protected)/admin/applications'
import { Route as protectedDashboardSettingsRouteRouteImport } from './routes/(protected)/dashboard/settings/route'
import { Route as protectedDashboardSettingsIndexRouteImport } from './routes/(protected)/dashboard/settings/index'
import { Route as protectedAdminLawyersIdRouteImport } from './routes/(protected)/admin/lawyers/$id'
import { Route as protectedAdminClientsIdRouteImport } from './routes/(protected)/admin/clients/$id'

const SubscriptionSuccessRoute = SubscriptionSuccessRouteImport.update({
  id: '/subscription-success',
  path: '/subscription-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSearchLawyerRoute = publicSearchLawyerRouteImport.update({
  id: '/(public)/search-lawyer',
  path: '/search-lawyer',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const authVerifyOtpRoute = authVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authNewPasswordRoute = authNewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const OnboardinglawyerRouteRoute = OnboardinglawyerRouteRouteImport.update({
  id: '/onboarding/(lawyer)',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingclientRouteRoute = OnboardingclientRouteRouteImport.update({
  id: '/onboarding/(client)',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAdminRouteRoute = protectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedDashboardRoute,
} as any)
const protectedAdminIndexRoute = protectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const OnboardinglawyerStatusRoute = OnboardinglawyerStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => OnboardinglawyerRouteRoute,
} as any)
const OnboardinglawyerReviewRoute = OnboardinglawyerReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OnboardinglawyerRouteRoute,
} as any)
const OnboardinglawyerLawyerSpecializationsRoute =
  OnboardinglawyerLawyerSpecializationsRouteImport.update({
    id: '/lawyer-specializations',
    path: '/lawyer-specializations',
    getParentRoute: () => OnboardinglawyerRouteRoute,
  } as any)
const OnboardinglawyerCredentialsRoute =
  OnboardinglawyerCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => OnboardinglawyerRouteRoute,
  } as any)
const OnboardinglawyerBasicsRoute = OnboardinglawyerBasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => OnboardinglawyerRouteRoute,
} as any)
const OnboardingclientClientSpecializationsRoute =
  OnboardingclientClientSpecializationsRouteImport.update({
    id: '/client-specializations',
    path: '/client-specializations',
    getParentRoute: () => OnboardingclientRouteRoute,
  } as any)
const OnboardingclientClientLocationRoute =
  OnboardingclientClientLocationRouteImport.update({
    id: '/client-location',
    path: '/client-location',
    getParentRoute: () => OnboardingclientRouteRoute,
  } as any)
const publicLawyerLawyerIdRoute = publicLawyerLawyerIdRouteImport.update({
  id: '/(public)/lawyer/$lawyerId',
  path: '/lawyer/$lawyerId',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardSearchLawyerRoute =
  protectedDashboardSearchLawyerRouteImport.update({
    id: '/search-lawyer',
    path: '/search-lawyer',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardPlansRoute = protectedDashboardPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => protectedDashboardRoute,
} as any)
const protectedAdminUsersRoute = protectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const protectedAdminStatisticsRoute =
  protectedAdminStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedAdminLawyersRoute = protectedAdminLawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const protectedAdminClientsRoute = protectedAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const protectedAdminApplicationsRoute =
  protectedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedDashboardSettingsRouteRoute =
  protectedDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardSettingsIndexRoute =
  protectedDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardSettingsRouteRoute,
  } as any)
const protectedAdminLawyersIdRoute = protectedAdminLawyersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => protectedAdminLawyersRoute,
} as any)
const protectedAdminClientsIdRoute = protectedAdminClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => protectedAdminClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/subscription-success': typeof SubscriptionSuccessRoute
  '/admin': typeof protectedAdminRouteRouteWithChildren
  '/onboarding': typeof OnboardingIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/new-password': typeof authNewPasswordRoute
  '/register': typeof authRegisterRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/dashboard': typeof protectedDashboardRouteWithChildren
  '/search-lawyer': typeof publicSearchLawyerRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRouteRouteWithChildren
  '/admin/applications': typeof protectedAdminApplicationsRoute
  '/admin/clients': typeof protectedAdminClientsRouteWithChildren
  '/admin/lawyers': typeof protectedAdminLawyersRouteWithChildren
  '/admin/statistics': typeof protectedAdminStatisticsRoute
  '/admin/users': typeof protectedAdminUsersRoute
  '/dashboard/plans': typeof protectedDashboardPlansRoute
  '/dashboard/search-lawyer': typeof protectedDashboardSearchLawyerRoute
  '/lawyer/$lawyerId': typeof publicLawyerLawyerIdRoute
  '/onboarding/client-location': typeof OnboardingclientClientLocationRoute
  '/onboarding/client-specializations': typeof OnboardingclientClientSpecializationsRoute
  '/onboarding/basics': typeof OnboardinglawyerBasicsRoute
  '/onboarding/credentials': typeof OnboardinglawyerCredentialsRoute
  '/onboarding/lawyer-specializations': typeof OnboardinglawyerLawyerSpecializationsRoute
  '/onboarding/review': typeof OnboardinglawyerReviewRoute
  '/onboarding/status': typeof OnboardinglawyerStatusRoute
  '/admin/': typeof protectedAdminIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/admin/clients/$id': typeof protectedAdminClientsIdRoute
  '/admin/lawyers/$id': typeof protectedAdminLawyersIdRoute
  '/dashboard/settings/': typeof protectedDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/subscription-success': typeof SubscriptionSuccessRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/new-password': typeof authNewPasswordRoute
  '/register': typeof authRegisterRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/search-lawyer': typeof publicSearchLawyerRoute
  '/admin/applications': typeof protectedAdminApplicationsRoute
  '/admin/clients': typeof protectedAdminClientsRouteWithChildren
  '/admin/lawyers': typeof protectedAdminLawyersRouteWithChildren
  '/admin/statistics': typeof protectedAdminStatisticsRoute
  '/admin/users': typeof protectedAdminUsersRoute
  '/dashboard/plans': typeof protectedDashboardPlansRoute
  '/dashboard/search-lawyer': typeof protectedDashboardSearchLawyerRoute
  '/lawyer/$lawyerId': typeof publicLawyerLawyerIdRoute
  '/onboarding/client-location': typeof OnboardingclientClientLocationRoute
  '/onboarding/client-specializations': typeof OnboardingclientClientSpecializationsRoute
  '/onboarding/basics': typeof OnboardinglawyerBasicsRoute
  '/onboarding/credentials': typeof OnboardinglawyerCredentialsRoute
  '/onboarding/lawyer-specializations': typeof OnboardinglawyerLawyerSpecializationsRoute
  '/onboarding/review': typeof OnboardinglawyerReviewRoute
  '/onboarding/status': typeof OnboardinglawyerStatusRoute
  '/admin': typeof protectedAdminIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/admin/clients/$id': typeof protectedAdminClientsIdRoute
  '/admin/lawyers/$id': typeof protectedAdminLawyersIdRoute
  '/dashboard/settings': typeof protectedDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/subscription-success': typeof SubscriptionSuccessRoute
  '/(protected)/admin': typeof protectedAdminRouteRouteWithChildren
  '/onboarding/(client)': typeof OnboardingclientRouteRouteWithChildren
  '/onboarding/(lawyer)': typeof OnboardinglawyerRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/new-password': typeof authNewPasswordRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/(protected)/dashboard': typeof protectedDashboardRouteWithChildren
  '/(public)/search-lawyer': typeof publicSearchLawyerRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/(protected)/dashboard/settings': typeof protectedDashboardSettingsRouteRouteWithChildren
  '/(protected)/admin/applications': typeof protectedAdminApplicationsRoute
  '/(protected)/admin/clients': typeof protectedAdminClientsRouteWithChildren
  '/(protected)/admin/lawyers': typeof protectedAdminLawyersRouteWithChildren
  '/(protected)/admin/statistics': typeof protectedAdminStatisticsRoute
  '/(protected)/admin/users': typeof protectedAdminUsersRoute
  '/(protected)/dashboard/plans': typeof protectedDashboardPlansRoute
  '/(protected)/dashboard/search-lawyer': typeof protectedDashboardSearchLawyerRoute
  '/(public)/lawyer/$lawyerId': typeof publicLawyerLawyerIdRoute
  '/onboarding/(client)/client-location': typeof OnboardingclientClientLocationRoute
  '/onboarding/(client)/client-specializations': typeof OnboardingclientClientSpecializationsRoute
  '/onboarding/(lawyer)/basics': typeof OnboardinglawyerBasicsRoute
  '/onboarding/(lawyer)/credentials': typeof OnboardinglawyerCredentialsRoute
  '/onboarding/(lawyer)/lawyer-specializations': typeof OnboardinglawyerLawyerSpecializationsRoute
  '/onboarding/(lawyer)/review': typeof OnboardinglawyerReviewRoute
  '/onboarding/(lawyer)/status': typeof OnboardinglawyerStatusRoute
  '/(protected)/admin/': typeof protectedAdminIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/admin/clients/$id': typeof protectedAdminClientsIdRoute
  '/(protected)/admin/lawyers/$id': typeof protectedAdminLawyersIdRoute
  '/(protected)/dashboard/settings/': typeof protectedDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/subscription-success'
    | '/admin'
    | '/onboarding'
    | '/forgot-password'
    | '/new-password'
    | '/register'
    | '/verify-otp'
    | '/dashboard'
    | '/search-lawyer'
    | '/dashboard/settings'
    | '/admin/applications'
    | '/admin/clients'
    | '/admin/lawyers'
    | '/admin/statistics'
    | '/admin/users'
    | '/dashboard/plans'
    | '/dashboard/search-lawyer'
    | '/lawyer/$lawyerId'
    | '/onboarding/client-location'
    | '/onboarding/client-specializations'
    | '/onboarding/basics'
    | '/onboarding/credentials'
    | '/onboarding/lawyer-specializations'
    | '/onboarding/review'
    | '/onboarding/status'
    | '/admin/'
    | '/dashboard/'
    | '/admin/clients/$id'
    | '/admin/lawyers/$id'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/subscription-success'
    | '/onboarding'
    | '/forgot-password'
    | '/new-password'
    | '/register'
    | '/verify-otp'
    | '/search-lawyer'
    | '/admin/applications'
    | '/admin/clients'
    | '/admin/lawyers'
    | '/admin/statistics'
    | '/admin/users'
    | '/dashboard/plans'
    | '/dashboard/search-lawyer'
    | '/lawyer/$lawyerId'
    | '/onboarding/client-location'
    | '/onboarding/client-specializations'
    | '/onboarding/basics'
    | '/onboarding/credentials'
    | '/onboarding/lawyer-specializations'
    | '/onboarding/review'
    | '/onboarding/status'
    | '/admin'
    | '/dashboard'
    | '/admin/clients/$id'
    | '/admin/lawyers/$id'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/login'
    | '/subscription-success'
    | '/(protected)/admin'
    | '/onboarding/(client)'
    | '/onboarding/(lawyer)'
    | '/(auth)/forgot-password'
    | '/(auth)/new-password'
    | '/(auth)/register'
    | '/(auth)/verify-otp'
    | '/(protected)/dashboard'
    | '/(public)/search-lawyer'
    | '/onboarding/'
    | '/(protected)/dashboard/settings'
    | '/(protected)/admin/applications'
    | '/(protected)/admin/clients'
    | '/(protected)/admin/lawyers'
    | '/(protected)/admin/statistics'
    | '/(protected)/admin/users'
    | '/(protected)/dashboard/plans'
    | '/(protected)/dashboard/search-lawyer'
    | '/(public)/lawyer/$lawyerId'
    | '/onboarding/(client)/client-location'
    | '/onboarding/(client)/client-specializations'
    | '/onboarding/(lawyer)/basics'
    | '/onboarding/(lawyer)/credentials'
    | '/onboarding/(lawyer)/lawyer-specializations'
    | '/onboarding/(lawyer)/review'
    | '/onboarding/(lawyer)/status'
    | '/(protected)/admin/'
    | '/(protected)/dashboard/'
    | '/(protected)/admin/clients/$id'
    | '/(protected)/admin/lawyers/$id'
    | '/(protected)/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SubscriptionSuccessRoute: typeof SubscriptionSuccessRoute
  OnboardingclientRouteRoute: typeof OnboardingclientRouteRouteWithChildren
  OnboardinglawyerRouteRoute: typeof OnboardinglawyerRouteRouteWithChildren
  publicSearchLawyerRoute: typeof publicSearchLawyerRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  publicLawyerLawyerIdRoute: typeof publicLawyerLawyerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription-success': {
      id: '/subscription-success'
      path: '/subscription-success'
      fullPath: '/subscription-success'
      preLoaderRoute: typeof SubscriptionSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/search-lawyer': {
      id: '/(public)/search-lawyer'
      path: '/search-lawyer'
      fullPath: '/search-lawyer'
      preLoaderRoute: typeof publicSearchLawyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/new-password': {
      id: '/(auth)/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof authNewPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/onboarding/(lawyer)': {
      id: '/onboarding/(lawyer)'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardinglawyerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/(client)': {
      id: '/onboarding/(client)'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingclientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/admin': {
      id: '/(protected)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof protectedAdminRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/admin/': {
      id: '/(protected)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof protectedAdminIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/onboarding/(lawyer)/status': {
      id: '/onboarding/(lawyer)/status'
      path: '/status'
      fullPath: '/onboarding/status'
      preLoaderRoute: typeof OnboardinglawyerStatusRouteImport
      parentRoute: typeof OnboardinglawyerRouteRoute
    }
    '/onboarding/(lawyer)/review': {
      id: '/onboarding/(lawyer)/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof OnboardinglawyerReviewRouteImport
      parentRoute: typeof OnboardinglawyerRouteRoute
    }
    '/onboarding/(lawyer)/lawyer-specializations': {
      id: '/onboarding/(lawyer)/lawyer-specializations'
      path: '/lawyer-specializations'
      fullPath: '/onboarding/lawyer-specializations'
      preLoaderRoute: typeof OnboardinglawyerLawyerSpecializationsRouteImport
      parentRoute: typeof OnboardinglawyerRouteRoute
    }
    '/onboarding/(lawyer)/credentials': {
      id: '/onboarding/(lawyer)/credentials'
      path: '/credentials'
      fullPath: '/onboarding/credentials'
      preLoaderRoute: typeof OnboardinglawyerCredentialsRouteImport
      parentRoute: typeof OnboardinglawyerRouteRoute
    }
    '/onboarding/(lawyer)/basics': {
      id: '/onboarding/(lawyer)/basics'
      path: '/basics'
      fullPath: '/onboarding/basics'
      preLoaderRoute: typeof OnboardinglawyerBasicsRouteImport
      parentRoute: typeof OnboardinglawyerRouteRoute
    }
    '/onboarding/(client)/client-specializations': {
      id: '/onboarding/(client)/client-specializations'
      path: '/client-specializations'
      fullPath: '/onboarding/client-specializations'
      preLoaderRoute: typeof OnboardingclientClientSpecializationsRouteImport
      parentRoute: typeof OnboardingclientRouteRoute
    }
    '/onboarding/(client)/client-location': {
      id: '/onboarding/(client)/client-location'
      path: '/client-location'
      fullPath: '/onboarding/client-location'
      preLoaderRoute: typeof OnboardingclientClientLocationRouteImport
      parentRoute: typeof OnboardingclientRouteRoute
    }
    '/(public)/lawyer/$lawyerId': {
      id: '/(public)/lawyer/$lawyerId'
      path: '/lawyer/$lawyerId'
      fullPath: '/lawyer/$lawyerId'
      preLoaderRoute: typeof publicLawyerLawyerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/search-lawyer': {
      id: '/(protected)/dashboard/search-lawyer'
      path: '/search-lawyer'
      fullPath: '/dashboard/search-lawyer'
      preLoaderRoute: typeof protectedDashboardSearchLawyerRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/plans': {
      id: '/(protected)/dashboard/plans'
      path: '/plans'
      fullPath: '/dashboard/plans'
      preLoaderRoute: typeof protectedDashboardPlansRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/admin/users': {
      id: '/(protected)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof protectedAdminUsersRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/statistics': {
      id: '/(protected)/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof protectedAdminStatisticsRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/lawyers': {
      id: '/(protected)/admin/lawyers'
      path: '/lawyers'
      fullPath: '/admin/lawyers'
      preLoaderRoute: typeof protectedAdminLawyersRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/clients': {
      id: '/(protected)/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof protectedAdminClientsRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/applications': {
      id: '/(protected)/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof protectedAdminApplicationsRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/dashboard/settings': {
      id: '/(protected)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof protectedDashboardSettingsRouteRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/settings/': {
      id: '/(protected)/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof protectedDashboardSettingsIndexRouteImport
      parentRoute: typeof protectedDashboardSettingsRouteRoute
    }
    '/(protected)/admin/lawyers/$id': {
      id: '/(protected)/admin/lawyers/$id'
      path: '/$id'
      fullPath: '/admin/lawyers/$id'
      preLoaderRoute: typeof protectedAdminLawyersIdRouteImport
      parentRoute: typeof protectedAdminLawyersRoute
    }
    '/(protected)/admin/clients/$id': {
      id: '/(protected)/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof protectedAdminClientsIdRouteImport
      parentRoute: typeof protectedAdminClientsRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authNewPasswordRoute: typeof authNewPasswordRoute
  authRegisterRoute: typeof authRegisterRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authNewPasswordRoute: authNewPasswordRoute,
  authRegisterRoute: authRegisterRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedAdminClientsRouteChildren {
  protectedAdminClientsIdRoute: typeof protectedAdminClientsIdRoute
}

const protectedAdminClientsRouteChildren: protectedAdminClientsRouteChildren = {
  protectedAdminClientsIdRoute: protectedAdminClientsIdRoute,
}

const protectedAdminClientsRouteWithChildren =
  protectedAdminClientsRoute._addFileChildren(
    protectedAdminClientsRouteChildren,
  )

interface protectedAdminLawyersRouteChildren {
  protectedAdminLawyersIdRoute: typeof protectedAdminLawyersIdRoute
}

const protectedAdminLawyersRouteChildren: protectedAdminLawyersRouteChildren = {
  protectedAdminLawyersIdRoute: protectedAdminLawyersIdRoute,
}

const protectedAdminLawyersRouteWithChildren =
  protectedAdminLawyersRoute._addFileChildren(
    protectedAdminLawyersRouteChildren,
  )

interface protectedAdminRouteRouteChildren {
  protectedAdminApplicationsRoute: typeof protectedAdminApplicationsRoute
  protectedAdminClientsRoute: typeof protectedAdminClientsRouteWithChildren
  protectedAdminLawyersRoute: typeof protectedAdminLawyersRouteWithChildren
  protectedAdminStatisticsRoute: typeof protectedAdminStatisticsRoute
  protectedAdminUsersRoute: typeof protectedAdminUsersRoute
  protectedAdminIndexRoute: typeof protectedAdminIndexRoute
}

const protectedAdminRouteRouteChildren: protectedAdminRouteRouteChildren = {
  protectedAdminApplicationsRoute: protectedAdminApplicationsRoute,
  protectedAdminClientsRoute: protectedAdminClientsRouteWithChildren,
  protectedAdminLawyersRoute: protectedAdminLawyersRouteWithChildren,
  protectedAdminStatisticsRoute: protectedAdminStatisticsRoute,
  protectedAdminUsersRoute: protectedAdminUsersRoute,
  protectedAdminIndexRoute: protectedAdminIndexRoute,
}

const protectedAdminRouteRouteWithChildren =
  protectedAdminRouteRoute._addFileChildren(protectedAdminRouteRouteChildren)

interface protectedDashboardSettingsRouteRouteChildren {
  protectedDashboardSettingsIndexRoute: typeof protectedDashboardSettingsIndexRoute
}

const protectedDashboardSettingsRouteRouteChildren: protectedDashboardSettingsRouteRouteChildren =
  {
    protectedDashboardSettingsIndexRoute: protectedDashboardSettingsIndexRoute,
  }

const protectedDashboardSettingsRouteRouteWithChildren =
  protectedDashboardSettingsRouteRoute._addFileChildren(
    protectedDashboardSettingsRouteRouteChildren,
  )

interface protectedDashboardRouteChildren {
  protectedDashboardSettingsRouteRoute: typeof protectedDashboardSettingsRouteRouteWithChildren
  protectedDashboardPlansRoute: typeof protectedDashboardPlansRoute
  protectedDashboardSearchLawyerRoute: typeof protectedDashboardSearchLawyerRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
}

const protectedDashboardRouteChildren: protectedDashboardRouteChildren = {
  protectedDashboardSettingsRouteRoute:
    protectedDashboardSettingsRouteRouteWithChildren,
  protectedDashboardPlansRoute: protectedDashboardPlansRoute,
  protectedDashboardSearchLawyerRoute: protectedDashboardSearchLawyerRoute,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
}

const protectedDashboardRouteWithChildren =
  protectedDashboardRoute._addFileChildren(protectedDashboardRouteChildren)

interface protectedRouteRouteChildren {
  protectedAdminRouteRoute: typeof protectedAdminRouteRouteWithChildren
  protectedDashboardRoute: typeof protectedDashboardRouteWithChildren
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedAdminRouteRoute: protectedAdminRouteRouteWithChildren,
  protectedDashboardRoute: protectedDashboardRouteWithChildren,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface OnboardingclientRouteRouteChildren {
  OnboardingclientClientLocationRoute: typeof OnboardingclientClientLocationRoute
  OnboardingclientClientSpecializationsRoute: typeof OnboardingclientClientSpecializationsRoute
}

const OnboardingclientRouteRouteChildren: OnboardingclientRouteRouteChildren = {
  OnboardingclientClientLocationRoute: OnboardingclientClientLocationRoute,
  OnboardingclientClientSpecializationsRoute:
    OnboardingclientClientSpecializationsRoute,
}

const OnboardingclientRouteRouteWithChildren =
  OnboardingclientRouteRoute._addFileChildren(
    OnboardingclientRouteRouteChildren,
  )

interface OnboardinglawyerRouteRouteChildren {
  OnboardinglawyerBasicsRoute: typeof OnboardinglawyerBasicsRoute
  OnboardinglawyerCredentialsRoute: typeof OnboardinglawyerCredentialsRoute
  OnboardinglawyerLawyerSpecializationsRoute: typeof OnboardinglawyerLawyerSpecializationsRoute
  OnboardinglawyerReviewRoute: typeof OnboardinglawyerReviewRoute
  OnboardinglawyerStatusRoute: typeof OnboardinglawyerStatusRoute
}

const OnboardinglawyerRouteRouteChildren: OnboardinglawyerRouteRouteChildren = {
  OnboardinglawyerBasicsRoute: OnboardinglawyerBasicsRoute,
  OnboardinglawyerCredentialsRoute: OnboardinglawyerCredentialsRoute,
  OnboardinglawyerLawyerSpecializationsRoute:
    OnboardinglawyerLawyerSpecializationsRoute,
  OnboardinglawyerReviewRoute: OnboardinglawyerReviewRoute,
  OnboardinglawyerStatusRoute: OnboardinglawyerStatusRoute,
}

const OnboardinglawyerRouteRouteWithChildren =
  OnboardinglawyerRouteRoute._addFileChildren(
    OnboardinglawyerRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SubscriptionSuccessRoute: SubscriptionSuccessRoute,
  OnboardingclientRouteRoute: OnboardingclientRouteRouteWithChildren,
  OnboardinglawyerRouteRoute: OnboardinglawyerRouteRouteWithChildren,
  publicSearchLawyerRoute: publicSearchLawyerRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  publicLawyerLawyerIdRoute: publicLawyerLawyerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
