/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRegisterAreasRouteImport } from './routes/onboarding/register-areas'
import { Route as OnboardingLocationRouteImport } from './routes/onboarding/location'
import { Route as authVerifyOtpRouteImport } from './routes/(auth)/verify-otp'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authNewPasswordRouteImport } from './routes/(auth)/new-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRegisterAreasRoute = OnboardingRegisterAreasRouteImport.update({
  id: '/onboarding/register-areas',
  path: '/onboarding/register-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLocationRoute = OnboardingLocationRouteImport.update({
  id: '/onboarding/location',
  path: '/onboarding/location',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyOtpRoute = authVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authNewPasswordRoute = authNewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/new-password': typeof authNewPasswordRoute
  '/register': typeof authRegisterRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/onboarding/register-areas': typeof OnboardingRegisterAreasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/new-password': typeof authNewPasswordRoute
  '/register': typeof authRegisterRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/onboarding/register-areas': typeof OnboardingRegisterAreasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/new-password': typeof authNewPasswordRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/onboarding/register-areas': typeof OnboardingRegisterAreasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/forgot-password'
    | '/new-password'
    | '/register'
    | '/verify-otp'
    | '/onboarding/location'
    | '/onboarding/register-areas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/forgot-password'
    | '/new-password'
    | '/register'
    | '/verify-otp'
    | '/onboarding/location'
    | '/onboarding/register-areas'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/login'
    | '/(auth)/forgot-password'
    | '/(auth)/new-password'
    | '/(auth)/register'
    | '/(auth)/verify-otp'
    | '/onboarding/location'
    | '/onboarding/register-areas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingLocationRoute: typeof OnboardingLocationRoute
  OnboardingRegisterAreasRoute: typeof OnboardingRegisterAreasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/register-areas': {
      id: '/onboarding/register-areas'
      path: '/onboarding/register-areas'
      fullPath: '/onboarding/register-areas'
      preLoaderRoute: typeof OnboardingRegisterAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/location': {
      id: '/onboarding/location'
      path: '/onboarding/location'
      fullPath: '/onboarding/location'
      preLoaderRoute: typeof OnboardingLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/new-password': {
      id: '/(auth)/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof authNewPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authNewPasswordRoute: typeof authNewPasswordRoute
  authRegisterRoute: typeof authRegisterRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authNewPasswordRoute: authNewPasswordRoute,
  authRegisterRoute: authRegisterRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingLocationRoute: OnboardingLocationRoute,
  OnboardingRegisterAreasRoute: OnboardingRegisterAreasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
